apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "pks-observability.prometheus-datasource.config-name" . }}
  labels:
    grafana_datasource: "true"
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://{{ template "pks-observability.prometheus-datasource.server-name" . }}:9090
        access: proxy
        isDefault: true